FROM mtgupf/essentia:ubuntu18.04-v2.1_beta5

# update system package
RUN apt-get update -y && apt-get -y install python3-pip ffmpeg

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . /usr/src/services
WORKDIR /usr/src/services

RUN pip3 install pipenv

# # Install solola transcription algorithm

# COPY ./prerequisites.sh /usr/src/services/prerequisites.sh
# RUN sh prerequisites.sh

# # Install http server and server framework

# COPY ./install_service_dependency.sh /usr/src/services/install_service_dependency.sh
# RUN sh install_service_dependency.sh

RUN pipenv install --sequential
